ProjectManagerDailies/dailies/urls.py
from django.urls import path

from . import views

app_name = 'dailies'
urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='index'),
    path('report/<int:pk>/view', views.ReportView.as_view(), name='report'),
    path('report/<int:pk>/edit', views.EditReportView.as_view(), name='edit_report'),
]

ProjectManagerDailies/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

ProjectManagerDailies/dailies/models.py
from django.conf import settings
from django.db import models


class Contractor(models.Model):
    ctr_code = models.CharField(max_length=10, primary_key=True, verbose_name="Contractor Code")
    company_name = models.CharField(max_length=150, verbose_name="Contractor Company Name")

    def __str__(self):
        return self.company_name


class Employee(models.Model):
    # id is the primary_key
    first_name = models.CharField(max_length=25, verbose_name="First Name")
    last_name = models.CharField(max_length=25, verbose_name="Last Name")
    labor_class = models.CharField(max_length=10, verbose_name="Labor Class")
    ctr_code = models.ForeignKey('Contractor', on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Employee_Report(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    report = models.ForeignKey('Report', on_delete=models.CASCADE)
    task_name = models.CharField(max_length=100, verbose_name= "Task Name")
    task_details = models.TextField(verbose_name= "Task Details")
    task_hours = models.DecimalField(decimal_places=1, max_digits=4, verbose_name= "Task Hours")

    def __str__(self):
        return '%s %s\'s Report - %s' % (self.employee.first_name, self.employee.last_name, str(self.report.date))


class Equipment(models.Model):
    name = models.CharField(max_length=100, verbose_name="Equipment Name")
    ctr_code = models.ForeignKey('Contractor', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Equipment_Report(models.Model):
    equipment = models.ForeignKey('Equipment', on_delete=models.CASCADE)
    report = models.ForeignKey('Report', on_delete=models.CASCADE)
    hours_used = models.DecimalField(decimal_places=1, max_digits=4, verbose_name="Hours Used")

    def __str__(self):
        return '%s Report - %s' % (self.equipment.name, str(self.report.date))


class Report(models.Model):
    date = models.DateField(verbose_name="Date")
    weather = models.CharField(max_length=200, verbose_name="Weather")
    user_pk = models.IntegerField(verbose_name="User PK")
    project = models.ForeignKey('Project', on_delete=models.CASCADE)

    def __str__(self):
        return '%s Report - %s' % (self.project.name, str(self.date))


class Project(models.Model):
    name = models.CharField(max_length=200, verbose_name="Project Name")
    number = models.IntegerField(verbose_name="Project Number")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="User")

    def __str__(self):
        return self.name

ProjectManagerDailies/dailies/forms.py
from django import forms

class ReportForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)
    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

ProjectManagerDailies/dailies/views.py
from django.views.generic import TemplateView, View
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect
from weasyprint import HTML
from .helper.data_helper import get_daily_report_info as daily_report
from django.views.generic.edit import FormView, UpdateView

from .models import Report
from .forms import ReportForm

class FrontendRenderView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'dailies/home.html', {})

class IndexTemplateView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user_reports = Report.objects.filter(user_pk=request.user.id)
            return render(request, 'dailies/index.html', {'user_reports':user_reports})
        else:
            return HttpResponseRedirect('/login/')

class EditReportView(UpdateView):
    # def get(self, request, *args, **kwargs):
    #     if request.user.is_authenticated:
    #         report = daily_report(self.kwargs.get('pk'))
    #         return render(request, "dailies/edit_report.html", {'report':report})
    #     else:
    #         return HttpResponseRedirect('/dailies/')

    template_name = 'dailies/edit_report.html'
    form_class = ReportForm
    success_url = '/dailies/'

    def get_initial(self):
        report = daily_report(self.kwargs.get('pk'))
        return {'your_name': 'test'}

    def get_success_url(self):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super().form_valid(form)

class ReportView(TemplateView):
    def to_pdf(self, report):
        html_string = render_to_string('dailies/report.html', {'report': report})
        html = HTML(string=html_string)
        pdf_name = 'Report_' + report['date'].replace('-','_') + '.pdf'
        html.write_pdf(target='dailies/tmp/' + pdf_name);

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            report = daily_report(self.kwargs.get('pk'))
            self.to_pdf(report)
            return render(request, 'dailies/report.html', {'report':report})
        else:
            return HttpResponseRedirect('/dailies/')

ProjectManagerDailies/dailies/templates/dailies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Project Manager Daily</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'dailies:index' %}">Project Manager Daily</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dailies:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if 'view' in request.path %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dailies:edit_report' report.report_id %}">Edit Report</a>
                    </li>
                {% elif 'edit' in request.path %}
                    <li class="nav-item">
{#                    CHANGE THIS SO YOU GET THE REPORT AS A DATA VARIABLE IN THE FORM#}
{#                        <a class="nav-link" href="{% url 'dailies:report' report.report_id %}">View Report</a>#}
                    </li>
                {%  endif %}
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link" href="/logout?next=/dailies/">Logout</a>
                    {% else %}
                        <a class="nav-link" href="/login">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    <br>
    {%  block content %}
    {%  endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script>
  var csrf_token = '{{ csrf_token }}'
</script>
</html>

ProjectManagerDailies/dailies/templates/dailies/edit_report.html
{% extends 'dailies/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send message">
    </form>
{% endblock %}

ProjectManagerDailies/dailies/templates/dailies/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Custom CSS -->
    {% comment "Load your css like so" %}
      <link rel="stylesheet" href="{% static 'css/my/app/app.css' %}">
    {% endcomment %}


    <title>Hello, world!</title>
</head>
<body>
<h1>Hello, world!</h1>

<div>
    <script src="D:/Users/Cookies/Documents/GPC_WebApp/React/src/App.js"></script>
</div>


</body>
</html>

ProjectManagerDailies/dailies/templates/dailies/index.html
{% extends 'dailies/base.html' %}

{% block content %}
    <div class="page-center container">
        {% if request.user.is_authenticated %}
            <span> Hello, {{ request.user.username}} below is a list of your reports:</span>
            {% for r in user_reports %}
                <li><a>{{ r }}</a></li>
                <ul>
                    <li><a href="{% url 'dailies:report' r.id %}">View</a></li>
                    <li><a href="{% url 'dailies:edit_report' r.id %}">Edit</a></li>
                </ul>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

ProjectManagerDailies/dailies/templates/dailies/report.html
{% extends 'dailies/base.html' %}

{% block content %}
    <div class="report content">
        <div class="d-flex w-100 justify-content-between">
            <h2 class="mb-1">Report #{{ report.report_id }} {{ report.date }}</h2>
        </div>
        <p class="mb-1">Project: {{ report.project_name }} #{{ report.project_number }}</p>
        <p class="mb-1">Weather: {{ report.weather }}</p>
        <br> {# Space between report head and columns #}
        <div class="row">
            <div class="col">
                <div class="equipment">
                    <table class="table table-sm table-hover">
                        <thead>
                        <h5><b>Equipment on Site</b></h5>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Hours</th>
                            <th scope="col">Contractor</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for key, value in report.eq_report.items%}
                            <tr>
                                <td>{{ value.eq_name }}</td>
                                <td>{{ value.contractor }}</td>
                                <td>{{ value.hours_used }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col">
                <div class="contractors">
                    <table class="table table-sm table-hover">
                        <thead>
                        <h5><b>Contractors</b></h5>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Ctr Code</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for key, value in report.contractors.items%}
                            <tr>
                                <td>{{ value.company_name }}</td>
                                <td>{{ value.ctr_code }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="w-100"></div>
        </div>
        <br> {# Space between columns and employee task #}
        <div class="employee">
            <div class="employee">
                <table class="table table-sm table-hover">
                    <thead>
                    <h5><b>Employee Tasks</b></h5>
                    <tr>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Labor Class</th>
                        <th scope="col">Contractor</th>
                        <th scope="col">Task Name</th>
                        <th scope="col">Details</th>
                        <th scope="col">Hours</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for key, value in report.e_report.items%}
                            <tr>
                                <td>{{ value.first_name }}</td>
                                <td>{{ value.last_name }}</td>
                                <td>{{ value.labor_class }}</td>
                                <td>{{ value.contractor }}</td>
                                <td>{{ value.task_name }}</td>
                                <td>{{ value.task_details }}</td>
                                <td>{{ value.task_hours }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}